### ISSUE TITLE
Set default value for "location" parameter

### ISSUE THREAD

**Issue by KoblerS** [Azure/bicep-deploy#115]
When creating a Bicep deployment at the resource group scope, the deployment fails if you provide a "location" parameter with given error message:

![Image](https://github.com/user-attachments/assets/4467a2a0-b236-4b02-998c-a85c5760b527)

Once I provide a default value e.g:

```yaml
- name: Deploy Bicep
   uses: azure/bicep-deploy@v1
   with:
     type: deployment
     location: ""
     operation: create
...
```

it works. But unfortunately location **must** be provided, better would be defaulting to ""

I do see that the current code sets the "location" parameter as not required but it seems like it is not released yet. Any ETA for the release?
