### ISSUE TITLE
Bicepparam files don't support `using none`

### ISSUE THREAD

**Issue by nnellans** [Azure/bicep-deploy#137]
I tested v2 of the action using the following:

```yaml
operation: 'create'
type: 'deployment'
scope: 'resourceGroup'
subscription-id: 'xxx'
resource-group-name: 'xxx'
template-file: 'main.bicep'
parameters-file: 'main.bicepparam'
```

If my `bicepparam` file is configured with `using none` then I get a deployment error:  The deployment 'azure-bicep-deploy' must have either the TemplateLink or Template property set.

Updating the `bicepparam` file to say `using 'main.bicep'` fixed the deployment.
