### ISSUE TITLE
Action passing with non-zero output

### ISSUE THREAD

**Issue by nu12** [Azure/bicep-deploy#149]
Hello.

The Github action is passing, even if the execution of the az deployment command exits with a non-zero output.

As an exemple, the following `main.bicep` file is incorrect, because the name parameters is required:
```
module storageAccount 'br/public:avm/res/storage/storage-account:0.18.0' = {
  name: 'storageAccountDeployment'
  params: {
    // Required parameters
    //name: 'ssablob001'
  }
}
```
If I run a `validate` locally, it gives an error and exits with code `1`:

<img width="1124" alt="Image" src="https://github.com/user-attachments/assets/21805927-9d0b-4203-bde6-22d31ecdf5c1" />

When running a workflow with the bicep-deploy action like so:
```
   - name: Validate
      uses: azure/bicep-deploy@v2
      with:
        type: deployment
        operation: validate
        name: Development
        scope: resourceGroup
        resource-group-name: azure
        subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
        template-file: ./main.bicep
        parameters-file: ./params.json
```
It results in the error message in the standard output, but the action completes with passing status.

![Image](https://github.com/user-attachments/assets/bae0a044-ca7e-4f49-8d7d-16a41b4ccc9c)

In fact the same happens to what-if and create: the error message in the output but a passing status in the actions and in the workflow as a whole.

This is causing confusion in my current project as users see the workflow completed with success only to discover later that it didn't work. In a more complex workflow, with several steps and dependencies, it is harder to track where the error is if no clear indication is given by the action.

The expected behaviour is to fail the action if the deployment fails. Either it fails by default with a flag to ignore it, or it passes by default (the current situation) with a flag to make it fail if the deployment fails.

The complete code to reproduce this scenario is here: https://github.com/nu12/azure-bicep-deploy

Thank you
