### ISSUE TITLE
Request for documentation: How to use GitHub Actions Variables as Parameters?

### ISSUE THREAD

**Issue by boldandbusted** [Azure/bicep-deploy#220]
Howdy. In the azure/arm-deploy Action (now deprecated), you could have parameters like this:

```
          parameters: >
            location=${{ vars.AZURE_LOCATION }}
            gitHubAppKey="${{ secrets.GH_APP_PRIVATE_KEY }}"
```

How can you do something similar with azure/bicep-deploy, since `parameters:` is now a JSON object? Or is this currently supported and under-documented? Thanks!

**Comment by MirzaMerdovic** [comment]
@boldandbusted you probably saw this ,but just in case there is an example [here](https://github.com/Azure/bicep-deploy/blob/main/examples/DEPLOYMENT.md)
```
- name: Deployment
  uses: azure/bicep-deploy@v2
  with:
    type: deployment
    operation: create
    name: Development
    scope: resourceGroup
    subscription-id: 00000000-0000-0000-0000-000000000000
    resource-group-name: example
    template-file: ./src/main.bicep
    parameters: '{"name": "Development", "tags": { "environment": "development" }}'
```
What is not clear to me is whether this can be used in combination with `parameters-file` and will `parameters` then override value in `parameters-file`, basically I don't understand how parameter precedence works here but maybe that's not important for you

**Comment by anthony-c-martin** [comment]
> Howdy. In the azure/arm-deploy Action (now deprecated), you could have parameters like this:
> 
> ```
>           parameters: >
>             location=${{ vars.AZURE_LOCATION }}
>             gitHubAppKey="${{ secrets.GH_APP_PRIVATE_KEY }}"
> ```
> 
> How can you do something similar with azure/bicep-deploy, since `parameters:` is now a JSON object? Or is this currently supported and under-documented? Thanks!

As of the latest release, YAML and JSON are both supported for complex values. My preferred approach would be:

```yml
- name: Deployment
  uses: azure/bicep-deploy@v2
  with:
    type: deployment
    ...
    parameters: |
      location: ${{ vars.AZURE_LOCATION }}
      gitHubAppKey: ${{ secrets.GH_APP_PRIVATE_KEY }}
```
