### ISSUE TITLE
Unable to deploy resources to Azure Government Cloud

### ISSUE THREAD

**Issue by ApoorvaSharmaTR** [Azure/bicep-deploy#80]
Unlike the old github action this one doesn't respect the "cloud" property set in the **_.bicepconfig_** file.

**Comment by ljtill** [comment]
@ApoorvaSharmaTR we've implemented support for the cloud property and would appreciate your help testing it before release. You can test it by pointing the `uses:` field to the branch with the proposed changes and setting the `environment:` input.

```yaml
- name: Deployment
  uses: azure/bicep-deploy@feat/endpoint
  with:
    type: deployment
    environment: azureUSGovernment
    ...
```

Let us know if you encounter any issues or have feedback!
