### ISSUE TITLE
Handling Deployment Outputs

### ISSUE THREAD

**Issue by matousrokos** [Azure/bicep-deploy#96]
Is there any way how to use deployment outputs so I can work with them in further steps? Was expecting something like:

```
         template-file: ./Modules/create-subscription.bicep
          parameters-file: 
          outputs: 
            subscriptionId: subscriptionId
      
      - name: Apply tag to subscription
        run: |
          az tag create --resource-id "/subscriptions/${{ steps.create_subscription.outputs.subscriptionId }}" --tags Owner='${{ steps.check-issue.outputs.Owner }}'
```

**Comment by anthony-c-martin** [comment]
@matousrokos this is already supported. We have unit tests to verify this, but I've added end-to-end tests with #103.

Here's a modified example from our CI, using the `steps.<steps_id>.outputs.<output_name>` actions syntax:
```yml
    - name: Test Deployment - Deploy
      id: test-deployment-create
      uses: ./
      with:
        type: deployment
        operation: create
        name: ci-deploy
        scope: resourceGroup
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resource-group-name: azure-bicep-deploy-ci
        parameters-file: test/files/basic/main.bicepparam

    - name: Print Deployment Outputs
      run: |
        echo "intOutput: ${{ steps.test-deployment-create.outputs.intOutput }}"
        echo "stringOutput: ${{ steps.test-deployment-create.outputs.stringOutput }}"
```

See [GitHub Docs](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/passing-information-between-jobs) on more general information for accessing step outputs.
